# common
SystemCommon.accCreateTime=created at (account common)
systemCommon.accCreateTime=created at (account common)
SystemCommon.accCreateAccName=created by (account common)
systemCommon.accCreateAccName=created by (account common)
SystemCommon.accLstUpdTime=last updated at (account common)
systemCommon.accLstUpdTime=last updated at (account common)
SystemCommon.accLstUpdAccName=last updated by (account common)
systemCommon.accLstUpdAccName=last updated by (account common)

# acc
acc.isValidOrNot=valid / invalid

# accAdmin
accAdmin.rawPassword=initial password
