##### app

### メール送信設定（FWでのシステムエラー発生時のメール送信にまだ使用されているので暫定的に記載）

# true or falseで記載
jp.ecuacion.lib.core.mail.smtp.authentication=true
# SMTP_SSL_ENABLEDは、通常jp.ecuacion.lib.core.mail.smtp.portが465であればtrue, 587であればfalse
jp.ecuacion.lib.core.mail.smtp.ssl-enabled=false
jp.ecuacion.lib.core.mail.smtp.server=mail.ecuacion.jp
jp.ecuacion.lib.core.mail.smtp.port=587
jp.ecuacion.lib.core.mail.smtp.sender=no-reply@ecuacion.jp
jp.ecuacion.lib.core.mail.smtp.password=LCL$saku!nore_Biz
jp.ecuacion.lib.core.mail.address-csv-on-system-error=yosuke.tanaka@ecuacion.jp
jp.ecuacion.lib.core.mail.smtp.checks-certificate=false
jp.ecuacion.lib.core.mail.smtp.bounce-address=yosuke.tanaka@ecuacion.jp
jp.ecuacion.lib.core.mail.debug=false
