AccRoleEnum.ACC_USER=user
AccRoleEnum.ACCOUNT_FULL_ACCESS=group admin
AccRoleEnum.ADMIN_FULL_ACCESS=system admin 
WebProtocolEnum.HTTP=http
WebProtocolEnum.HTTPS=https
CloudServiceKindEnum.AWS=AWS
CloudServiceKindEnum.WEB_ARENA_INDIGO=WebARENA Indigo
CloudServiceKindEnum.SAKURA_CLOUD=sakura cloud
RemoteServerKindEnum.HTTP_PROXY=HTTP Proxy
RemoteServerKindEnum.MONITORING=MONITORING
MailAuthKindEnum.ACC_NEW=new account
MailAuthKindEnum.ACC_PASSWORD_RESET=password reset
MailAuthKindEnum.ACC_MAIL_ADDRESS_CHANGED=mail address changed
