systemCommon.createAccId=create account ID
systemCommon.createAccName=create account name
systemCommon.createTime=create time
systemCommon.lstUpdAccId=last update account ID
systemCommon.lstUpdAccName=last update account name
systemCommon.lstUpdTime=last update time
systemCommon.delFlg=delete flag
systemCommon.version=version
acc.id=ID
acc.mailAddress=mail address
acc.name=name
acc.isAdmin=is system administrator
acc.role=role
acc.hashedPassword=hashed password
acc.isValid=valid
acc.isAuthenticated=authenticated
acc.hasLoggedIn=has logged in
accAdmin.accId=account ID
accGeneral.accId=account ID
accGeneral.accessibleToAllApps=accessible to all apps
agreement.id=ID
agreement.uploadedDatetime=uploaded datetime
accAgreement.id=ID
accAgreement.accId=account ID
accAgreement.agreementId=agreement version
mailAuthManagement.id=ID
mailAuthManagement.accId=account ID
mailAuthManagement.authKind=authentication kind
mailAuthManagement.authCode=authentication code
mailAuthManagement.isValid=valid
mailAuthManagement.hasUsed=used
mailAuthManagement.newMailAddress=new mail address
mailAuthManagement.newPassword=new password
mailAuthManagement.mailSentDatetime=mail sent datetime
qiitaUser.id=ID
qiitaUser.accId=account ID
qiitaUser.userIdInQiitaWebsite=Qiita user ID
qiitaUser.permanentId=permanent ID
qiitaUser.name=name
qiitaUser.description=description
qiitaUser.location=location
qiitaUser.organization=organization
qiitaUser.followeesCount=followees count
qiitaUser.followersCount=followers count
qiitaUser.itemsCount=items count
qiitaUser.profileImageUrl=profile image URL
qiitaUser.websiteUrl=website URL
qiitaUser.twitterScreenName=Twitter screen name
qiitaUser.githubLoginName=GitHub login name
qiitaUser.facebookId=Facebook ID
qiitaUser.linkedinId=LinkedIn ID
qiitaUser.isTeamOnly=team only
qiitaGroup.id=ID
qiitaGroup.accId=account ID
qiitaGroup.urlName=URL name
qiitaGroup.name=name
qiitaGroup.description=description
qiitaGroup.isPrivate=private
qiitaGroup.createdAt=created at
qiitaGroup.updatedAt=updated at
qiitaItem.id=ID
qiitaItem.accId=account ID
qiitaItem.itemIdInQiitaWebsite=item ID in Qiita website 
qiitaItem.coediting=coediting
qiitaItem.commentsCount=comments count
qiitaItem.createdAt=created at
qiitaItem.qiitaGroupId=Qiita group ID
qiitaItem.likesCount=likes count
qiitaItem.isPrivate=private
qiitaItem.reactionsCount=reactions count
qiitaItem.stocksCount=stocks count
qiitaItem.title=title
qiitaItem.updatedAt=updated at
qiitaItem.url=URL
qiitaItem.qiitaUserId=Qiita user ID
qiitaItem.pageViewsCount=page views count
qiitaItem.teamMembershipName=team membership name
qiitaItem.organizationUrlName=organization URL name
qiitaItem.isSlide=slide
qiitaTag.id=ID
qiitaTag.accId=account ID
qiitaTag.name=name
qiitaItemTag.id=ID
qiitaItemTag.accId=account ID
qiitaItemTag.qiitaItemId=Qiita item ID
qiitaItemTag.qiitaTagId=Qiita tag ID
qiitaItemTagVersion.id=ID
qiitaItemTagVersion.accId=account ID
qiitaItemTagVersion.qiitaItemTagId=Qiita item tag ID
qiitaItemTagVersion.versionName=version name
