# spring

## DB接続設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/qiita_data_viewer
spring.datasource.username=qiita_data_viewer
spring.datasource.password=samplePassword

# ecuacion
jp.ecuacion.lib.core.mail.title-prefix=（LOCAL環境：管理者メール）[qiita_data_viewer] 

# app

## common
profile=local

## proxy設定
PROXY_USES=false
PROXY_HOST=
PROXY_PORT=
PROXY_USERNAME=
PROXY_PASSWORD=
