# spring
spring.main.banner-mode=off
spring.profiles.active=profile
spring.messages.basename=messages,messages_core,messages_lib_core,field_names,field_names_base,ValidationMessages
spring.batch.job.enabled=true
spring.batch.job.name=allJobs

# ecuacion
jp.ecuacion.locale.use-root=true
