<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2012 ecuacion.jp (info@ecuacion.jp)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>qiita-data-viewer</artifactId>
	<packaging>war</packaging>
	<parent>
		<groupId>jp.ecuacion.app.qiita-data-viewer</groupId>
		<artifactId>qiita-data-viewer-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	
	<properties>
		<altDeploymentRepository>ecuacion-repo-sftp-private::${repository.ecuacion-repo-sftp-private-root}/profile-${mvn.prof-id}</altDeploymentRepository>
	</properties>
	
	<build>

		<resources>
			<resource><directory>src/main/resources</directory></resource>
			<resource>
				<directory>src/envs/${mvn.prof-id}/resources</directory>
				<includes><include>**/*.*</include></includes>
			</resource>
			<resource>
				<directory>src/main/java</directory>
				<excludes><exclude>**/*.java</exclude></excludes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
			</testResource>
		</testResources>
	</build>
	<dependencies>

		<!-- spring boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<!-- ecuacion-splib -->
		<dependency>
			<groupId>jp.ecuacion.splib</groupId>
			<artifactId>ecuacion-splib-web-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>

		<!-- dependent modules in the same project -->
		<dependency>
			<groupId>jp.ecuacion.app.${app.name}</groupId>
			<artifactId>${app.name}-core</artifactId>
		</dependency>

		<!-- other -->
		
		<!-- Random string generation for password -->
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		</dependency>

		<!-- XML processing -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		
		<!-- captcha -->
		<dependency>
			<groupId>net.logicsquad</groupId>
			<artifactId>nanocaptcha</artifactId>
			<version>2.1</version>
		</dependency>
		
	</dependencies>
</project>
